cluster_name: ""
ingress:
  kind: ""
  class: ""
  base_domain_name: ""
  annotations: {}
chart_name: "vcluster-k8s"
# chart_name: "vcluster-k3s"
chart_repo: "null"
chart_version: "null"
kubernetes_version: "1.25.2"
serviceCIDR: "192.168.0.0/16"
service:
  type: "LoadBalancer"
  loadBalancerSourceRanges: []
  loadBalancerSourceRangesString: ""
