{{if eq .Values.cluster_type "eks" }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{.Values.cluster_name}}
  labels:
    app: {{.Values.cluster_name}}
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: {{.Values.cluster_name}}-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: {{.Values.cluster_name}}-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: {{.Values.cluster_name}}-control-plane
spec:
  eksClusterName: {{.Values.cluster_name}}
  endpointAccess:
    public: true
    private: true
{{- if .Values.allowed_cidr_block }}
    publicCIDRs:
{{- .Values.allowed_cidr_block | toYaml | nindent 4 }}
{{- end}}
  roleAdditionalPolicies:
  - "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
  region: {{.Values.region}}
  sshKeyName: {{.Values.ssh_keyname}}
  version: v1.22
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: EKSConfigTemplate
metadata:
  name: {{.Values.cluster_name}}-0
spec:
  template: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{.Values.cluster_name}}-az1
spec:
  clusterName: {{.Values.cluster_name}}
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: {{.Values.cluster_name}}-0
      clusterName: {{.Values.cluster_name}}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: {{.Values.cluster_name}}-az1
      version: v1.22.10
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{.Values.cluster_name}}-az2
spec:
  clusterName: {{.Values.cluster_name}}
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: {{.Values.cluster_name}}-0
      clusterName: {{.Values.cluster_name}}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: {{.Values.cluster_name}}-az2
      version: v1.22.10
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{.Values.cluster_name}}-az3
spec:
  clusterName: {{.Values.cluster_name}}
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: {{.Values.cluster_name}}-0
      clusterName: {{.Values.cluster_name}}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: {{.Values.cluster_name}}-az3
      version: v1.22.10
{{end}}
